export const formTranslated = {
  jobName: 'Cargo',
  withExperience: 'Com Experiência',
  withoutExperience: 'Sem Experiência',
  noInstruction: 'Sem Instrução',
  elementarySchool: 'Ensino Fundamental',
  elementarySchoolIncomplete: 'Ensino Fundamental Incompleto',
  secondarySchool: 'Ensino médio',
  secondarySchoolIncomplete: 'Ensino Médio Incompleto',
  vocationalSchool: 'Ensino técnico',
  vocationalSchoolIncomplete: 'Ensino Técnico Incompleto',
  higherEducation: 'Ensino Superior',
  higherEducationIncomplete: 'Ensino Superior Incompleto',
  postGraduate: 'Pós-Graduação',
  postGraduateIncomplete: 'Pós-Graduação Incompleta',
  doctoral: 'Doutorado',
  doctoralIncomplete: 'Doutorado Incompleto',
  postDoctoral: 'Pós-Doutorado',
  postDoctoralIncomplete: 'Pós-Doutorado Incompleto',
  female: 'Feminino',
  male: 'Masculino',
  withPCD: 'É PCD',
  withoutPCD: 'Não é PCD',
  catA: 'A',
  catB: 'B',
  catC: 'C',
  catD: 'D',
  catE: 'E',
  morning: 'Manhã',
  afternoon: 'Tarde',
  night: 'Noite',
  saturday: 'Sábado',
  sunday: 'Domingo',
  travel: 'Viagem',
  basico: 'Básico',
  intermediario: 'Intermediário',
  avancado: 'Avançado',
  fluente: 'Fluente',
  onlyYoungApprentice: 'É Jovem Aprendiz',
  withoutYoungApprentice: 'Não é Jovem Aprendiz',
  withVehicle: 'Com Veículo',
  withoutVehicle: 'Sem Veículo',
  withDependents: 'Com Dependentes',
  withoutDependents: 'Sem Dependentes',
}
